---
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: check-ast
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch # No (direct) commits to master
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v1.0.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.18
    hooks:
      - id: isort
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
      - id: forbid-crlf
        files: \.md$
      - id: remove-crlf
        files: \.md$
  - repo: local
    hooks:
      - id: lint
        name: tox lint
        entry: tox -e lint
        language: system
