dist: xenial

language: python

os:
  - linux

python:
  - '3.6'
  - '3.7'

install:
  - python -m pip install -U pip setuptools pipenv
  - python -m pipenv install --dev
  - python -m pip install -e .

script:
  - tox -e lint
  - tox -e isort
  - tox -e mypy

